# Generated by Django 5.2.3 on 2025-06-17 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='codeblock',
            name='code',
            field=models.TextField(blank=True),
        ),
        migrations.AlterUniqueTogether(
            name='codeblock',
            unique_together={('snippet', 'language')},
        ),
    ]
