# Generated by Django 5.2.3 on 2025-06-17 06:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_codeblock_code_alter_codeblock_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='codeblock',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='codeblock',
            name='css_code',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='codeblock',
            name='html_code',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='codeblock',
            name='js_code',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='codeblock',
            name='snippet',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='code_block', to='api.snippet'),
        ),
        migrations.RemoveField(
            model_name='codeblock',
            name='code',
        ),
        migrations.RemoveField(
            model_name='codeblock',
            name='language',
        ),
    ]
